const triviaFacts = [
  "The Eiffel Tower can be 15 cm taller during hot days.",
  "Bananas are berries, but strawberries are not.",
  "Octopuses have three hearts.",
  "The human nose can detect over 1 trillion smells.",
  "Honey never spoils. Archaeologists found 3000-year-old honey in tombs!",
  "Sharks have been around longer than dinosaurs.",
  "A day on Venus is longer than a year on Venus.",
  "There are more stars in the universe than grains of sand on Earth.",
  "Your brain uses about 20% of your body's oxygen.",
  "Wombat poop is cube-shaped.",
  "A bolt of lightning is five times hotter than the sun.",
  "Sloths can hold their breath longer than dolphins.",
  "Hot water freezes faster than cold water. (Mpemba Effect)",
  "The heart of a blue whale is as big as a small car.",
  "Saturn could float in water because it's mostly gas.",
  "Some turtles can breathe through their butts.",
  "There's enough DNA in your body to stretch from the sun to Pluto and back.",
  "Birds are the closest living relatives of dinosaurs.",
  "A group of flamingos is called a 'flamboyance'.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "It rains diamonds on Jupiter and Saturn.",
  "The moon has moonquakes.",
  "Butterflies can taste with their feet.",
  "There's a species of jellyfish that's biologically immortal.",
  "Humans share 60% of their DNA with bananas.",
  "The longest hiccuping spree lasted 68 years.",
  "Some cats are allergic to humans.",
  "The majority of dust in your home is made from dead skin.",
  "A teaspoon of neutron star would weigh about 6 billion tons.",
  "Koalas have fingerprints that are almost indistinguishable from humans."
];